### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Killer74-hub** [HugoXOX3/PythonMiner#7]
~/PythonMiner $ python SoloMiner.py

⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣴⣶⣾⣿⣿⣿⣿⣷⣶⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣠⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠀⠀⠀
⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀
⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⠟⠿⠿⡿⠀⢰⣿⠁⢈⣿⣿⣿⣿⣿⣿⣿⣿⣦⠀⠀
⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣤⣄⠀⠀⠀⠈⠉⠀⠸⠿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀
⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⢠⣶⣶⣤⡀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⡆
⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠼⣿⣿⡿⠃⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣷
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⢀⣀⣀⠀⠀⠀⠀⢴⣿⣿⣿⣿⣿⣿⣿⣿⣿
⢿⣿⣿⣿⣿⣿⣿⣿⢿⣿⠁⠀⠀⣼⣿⣿⣿⣦⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⡿
⠸⣿⣿⣿⣿⣿⣿⣏⠀⠀⠀⠀⠀⠛⠛⠿⠟⠋⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⠇
⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⣤⡄⠀⣀⣀⣀⣀⣠⣾⣿⣿⣿⣿⣿⣿⣿⡟⠀
⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿⣄⣰⣿⠁⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀⠀
⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⢿⣿⣿⣿⣿⡿⠿⠟⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀
          M I N I N G
         B I T C O I N

  BTC ADDRESS:  bc1qw5a9enqxkt3yrw07v7jkertga85llxy3n573sn
  Donate BTC to HCMLXOX?:  bc1qnk0ftxa4ep296phhnxl5lv9c2s5f8xakpcxmth
 [ 19:36:05.509382 ]  [*] Subscribe thread()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 500, in thread_new_block
    ret = block_listener(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in block_listener
    responses = [json.loads(res) for res in response.decode().split('\n') if
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in <listcomp>
    responses = [json.loads(res) for res in response.decode().split('\n') if
                 ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 887 (char 886)
 [ 19:36:08.097116 ]  [*] Subscribe thread()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 500, in thread_new_block
    ret = block_listener(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in block_listener
    responses = [json.loads(res) for res in response.decode().split('\n') if
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in <listcomp>
    responses = [json.loads(res) for res in response.decode().split('\n') if
                 ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 954 (char 953)
 [ 19:36:08.820005 ]  [*] Subscribe thread started.
  [ 19:36:08.820932 ]  [*] Miner()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 475, in thread_bitcoin_miner
    ret = bitcoin_miner(self)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 191, in bitcoin_miner
    target = (ctx.nbits[2:] + '00' * (int(ctx.nbits[:2], 16) - 3)).zfill(64)
              ~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
 [ 19:36:10.680528 ]  [*] Subscribe thread()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 500, in thread_new_block
    ret = block_listener(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in block_listener
    responses = [json.loads(res) for res in response.decode().split('\n') if
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 426, in <listcomp>
    responses = [json.loads(res) for res in response.decode().split('\n') if
                 ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 954 (char 953)
  [ 19:36:10.824129 ]  [*] Miner()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 475, in thread_bitcoin_miner
    ret = bitcoin_miner(self)
          ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PythonMiner/SoloMiner.py", line 191, in bitcoin_miner
    target = (ctx.nbits[2:] + '00' * (int(ctx.nbits[:2], 16) - 3)).zfill(64)
              ~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
^C [ 19:36:12.306922 ]  Force Close, Please Wait..

**Comment by HugoXOX3** [comment]
Bad Network Environment,try to use a VPN or using another wifi that can connect

**Comment by Killer74-hub** [comment]
> Bad Network Environment,try to use a VPN or using another wifi that can connect

Doesn't have to do with that i think . I use Public Pool.io . will it Work?

**Comment by Killer74-hub** [comment]
> Bad Network Environment,try to use a VPN or using another wifi that can connect

Json exception. Could you fix it?

**Comment by HugoXOX3** [comment]
![Uploading Screenshot_2024-07-08-13-13-27-778_com.termux.jpg…]()

**Comment by HugoXOX3** [comment]
The reason of json exception is because we get the latest block information from there like block height,txIndex,etc.As a result,if you can't get the block information (json).The error occurred

**Comment by HugoXOX3** [comment]
> > Bad Network Environment,try to use a VPN or using another wifi that can connect
> 
> Doesn't have to do with that i think . I use Public Pool.io . will it Work?

Take a look at line 108.We need the get the information from Blockchain api

**Comment by Killer74-hub** [comment]
> > > Bad Network Environment,try to use a VPN or using another wifi that can connect
> > 
> > Doesn't have to do with that i think . I use Public Pool.io . will it Work?
> 
> Take a look at line 108.We need the get the information from Blockchain api

It hast json2.0

**Comment by HugoXOX3** [comment]
Try to ping that

**Comment by Killer74-hub** [comment]
> Try to ping that

No, it has a json2.0 encryption and decryption

https://www.jsonrpc.org/specification
